{% set name = "vulture" %}
{% set version = "2.10" %}
{% set sha256 = "2a5c3160bffba77595b6e6dfcc412016bd2a09cd4b66cdf7fbba913684899f6f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - vulture = vulture.core:main

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - toml

test:
  requires:
    - pip
    - coverage
    - pint
    - pytest
    - pytest-cov
  imports:
    - vulture
  source_files:
    - tests
  commands:
    - pip check
    - vulture --help
    - pytest --cov vulture --cov-report=html --cov-report=term --cov-report=xml --cov-append

about:
  home: https://github.com/jendrikseipp/vulture
  license: MIT
  license_file: LICENSE.txt
  summary: Find dead code

extra:
  recipe-maintainers:
    - Zeitsperre
    - jakirkham
