{% set name = "vulture" %}
{% set version = "2.9.1" %}
{% set sha256 = "b6a2aa632b6fd51488a8eeac650ab4a509bb1a032e81943817a8a2e6a63a30b3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - vulture = vulture.core:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - toml

test:
  requires:
    - pip
  imports:
    - vulture
  commands:
    - pip check
    - vulture --help

about:
  home: https://github.com/jendrikseipp/vulture
  license: MIT
  license_file: LICENSE.txt
  summary: Find dead code

extra:
  recipe-maintainers:
    - jakirkham
